version: "3"

services:

  vsftpd:
    image: fauria/vsftpd
    restart: always
    environment:
      FTP_USER: "test"
      FTP_PASS: "test"

    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21110:21100-21110
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd