version: "2.1"
services:
  # https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs
    restart: always
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ./nfs-storage:/data
    ports:
      - 2049:2049
