version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
      
    volumes:
      - conf:/etc/nginx/conf.d
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
    networks:
      - proxy
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - nginx-proxy
    networks: 
      - proxy
    environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

volumes:
  conf: 
  vhost:
  dhparam:
  certs:
  html:

networks:
  proxy:
    name: nginx-proxy
    external: true